# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """$directory$character"""
right_format = """$all"""

[character]
success_symbol = "[➜](bold green)"
vicmd_symbol = "[❮](bold purple)"

[nodejs]
disabled = true

[golang]
disabled = true

[package]
disabled = true

[gcloud]
disabled = true

[aws]
symbol='aws'

[kubernetes]
disabled = false
format='[$symbol$context(\($namespace\))]($style) '

[direnv]
disabled = true

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
